export default [
    'What celebrity do most people say you look like?',
    'If you could try any food, what would it be?',
    'What did you want to be when you grew up?',
    'Would you rather live in a city or a town?',
    'What is your favorite color and why?',
    'Which movie made you laugh the most?',
    'Do you know how to speak more than one language?',
    'How would you rate your laugh out of 10?',
    'How tall are you?',
    'Who is your favorite Disney character?',
    'Do you prefer big dogs or small dogs?',
    'Which of your teachers is most memorable and why?',
    'Would you rather stay at a hotel or an AirBNB?',
    'What is your hobby?',
    'What piece of advice would you share with your younger self?',
    'What is your “when I was your age…” story?',
    'Which beverage goes best with pizza?',
    'What is your standard office lunch?',
    'What do your family and friends think you do all day?',
    'How would you describe your job to a five year old?',
    'Where is your favorite vacation spot?',
    'What is the best dessert?',
    'What is your favorite season?',
    'What is the best kitchen gadget?',
    'Are you more productive in the morning or at night?',
    'What is your most used phone app?',
    'Which trap in Home Alone was the best?',
    'Does your car have a name? What is it?',
    'What is a weird fact you know?',
    'Pull out your phone; what is your most used emoji?'
];